# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17OImWgrRDCn2qxs3Tlp_vKfe2vrttiLZ
"""

import altair as alt
import numpy as np
import pandas as pd
import streamlit as st
import joblib
from inference import HealthPredictor

# --- 1. CONFIGURATION & FUNCTIONS ---
st.set_page_config(page_title="Health Policy Simulator", layout="wide")

def generate_policy_insights(inputs, prediction):
    """
    Analyzes inputs and prediction to generate government-level policy recommendations.
    """
    insights = []

    # Extract values safely
    wheat_val = inputs.get('Cereal Consumption Wheat', 0)
    sugar_val = inputs.get('Diet Composition Sugar', 0)
    veg_val = inputs.get('Vegetable Consumption', 0)
    # Note: Ensure the key here matches what is in your user_input dict below
    pulses_val = inputs.get('Diet Composition Pulses', 0)

    # A. Wheat Logic
    if wheat_val > 180:
         insights.append({
            "type": "warning",
            "text": f"🚨 **Supply Chain Alert:** Wheat intake ({wheat_val}kg) is critically high. Reducing dependency could significantly lower mortality risk."
        })
    elif wheat_val > 150:
        insights.append({
            "type": "info",
            "text": "🌾 **Policy Recommendation:** Wheat consumption is high. Subsidize alternative grains (rye, oats) to diversify the national diet."
        })

    # B. Sugar Logic
    if sugar_val > 12:
        insights.append({
            "type": "info",
            "text": "🍬 **Fiscal Policy:** Sugar intake indicates high metabolic risk. Propose a **Sugar-Sweetened Beverage (SSB) Tax**."
        })

    # C. Vegetable/Pulse Logic
    if veg_val < 180:
        insights.append({
            "type": "info",
            "text": "🥗 **Agricultural Subsidy:** Vegetable intake is low. Implement VAT reductions on fresh produce."
        })

    if pulses_val < 1.0:
        insights.append({
            "type": "success",
            "text": "💡 **Quick Win:** Increasing **Pulse (Bean) consumption** is a high-ROI intervention for this demographic."
        })

    # D. Overall Mortality Logic
    if prediction > 15.0:
        insights.append({
            "type": "error",
            "text": "⚠️ **CRITICAL:** Projected mortality rates exceed safety thresholds. Immediate multi-sector intervention required."
        })

    return insights

# --- 2. INITIALIZE PREDICTOR ---
@st.cache_resource
def get_predictor():
    return HealthPredictor()

predictor = get_predictor()

# --- 3. SIDEBAR: CONTROLS ---
st.sidebar.title("🇹🇷 Policy Controls")
st.sidebar.markdown("**Target:** Cardiovascular Mortality Rate")

# Demographics
st.sidebar.subheader("Demographics")
age = st.sidebar.slider("% Population Aged 65+", 5.0, 25.0, 9.0)
gender_label = st.sidebar.radio("Gender Focus", ["Both", "Female", "Male"], index=0)
gender_map = {"Both": 0, "Female": 1, "Male": 2}
gender_val = gender_map[gender_label]

# Key Diet Drivers
st.sidebar.subheader("Dietary Staples")
wheat = st.sidebar.slider("Wheat Consumption (kg)", 50, 250, 180, help="Turkey Avg: ~200kg")
veg = st.sidebar.slider("Vegetable Consumption (kg)", 50, 250, 200)
pulses = st.sidebar.slider("Pulses/Beans (kcal %)", 0.0, 5.0, 1.5)
sugar = st.sidebar.slider("Sugar (kcal %)", 0.0, 20.0, 10.0)
fat = st.sidebar.slider("Total Fat (kcal %)", 10.0, 40.0, 25.0)

# --- 4. MAIN PAGE ---
st.title("🇹🇷 AI Health Policy Simulator")
st.markdown("""This tool uses a **Random Forest** model to simulate how nutritional habits impact heart disease mortality.""")

# --- 5. RUN PREDICTION ---
if st.button("Run Simulation", type="primary"):

    # A. Package User Input
    # IMPORTANT: We use the variable 'user_inputs' (plural) to be consistent
    user_inputs = {
        '% Population Aged 65+': age,
        'Gender': gender_val,
        'Cereal Consumption Wheat': wheat,
        'Vegetable Consumption': veg,
        'Diet Composition Pulses': pulses,
        'Diet Composition Sugar': sugar,
        'Diet Calories Fat': fat
    }

    # B. Get Prediction
    result = predictor.predict(user_inputs)

    # C. Display Results
    if "error" in result:
        st.error(f"Prediction Failed: {result['error']}")
    else:
        rate = result['mortality_rate']

        # --- Top Metrics Row ---
        col1, col2 = st.columns(2)
        col1.metric("Predicted Mortality Rate", f"{rate:.2f}%")

        # Wheat Warning Badge
        # Now this works because 'user_inputs' exists!
        wheat_check = user_inputs.get('Cereal Consumption Wheat', 0)
        if wheat_check > 150:
            col2.metric("Wheat Risk Level", "High Risk 🚨", "Diminishing Returns Zone")
        else:
            col2.metric("Wheat Risk Level", "Optimal ✅")

        # --- Insights Section ---
        st.divider()
        st.subheader("💡 Policy Insights")

        # Call the function defined at the top
        policy_tips = generate_policy_insights(user_inputs, rate)

        if not policy_tips:
            st.info("✅ Current dietary parameters are within a stable policy range.")
        else:
            for tip in policy_tips:
                if tip["type"] == "warning":
                    st.warning(tip["text"])
                elif tip["type"] == "error":
                    st.error(tip["text"])
                elif tip["type"] == "success":
                    st.success(tip["text"])
                else:
                    st.info(tip["text"])

else:
    st.info("👈 Adjust the policy sliders in the sidebar to start.")