# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ri27Pq0LE_xmBUEascyjpujkM0KdxJ42
"""

import os
import pandas as pd

# --- PATHS ---
# Define the project structure based on the assumption you save this in src/
# BASE_DIR is the 'src' folder
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
# DATA_PATH points to '../data/UnifiedDataset.csv'
DATA_PATH = os.path.join(BASE_DIR, '../data/UnifiedDataset.csv')

#Use os.path.join with '..' to point to the root (main) folder
MODEL_PATH = os.path.join(BASE_DIR, 'final_model.pkl')
FEATURE_PATH = os.path.join(BASE_DIR, 'feature_names.pkl')

# --- FEATURE LISTS ---
# 1. RAW INPUTS (10 Features)
INPUT_FEATURES = [
    '% Population Aged 65+',
    'Gender',
    '% Population Aged 0-14',
    'Diet Composition Pulses',
    'Diet Composition Sugar',
    'Diet Calories Fat',
    'Cereal Consumption Wheat',
    'Vegetable Consumption',
    'Cereal Consumption Rice',
    'Fruit Consumption Oranges And Mandarines'
]

# 2. MODEL INPUTS (12 Features) - What the model expects
MODEL_FEATURES = INPUT_FEATURES + [
    'Risk_Metabolic_Combo',
    'Ratio_Veg_to_Grain'
]

# --- BUSINESS RULES: DEFAULTS CALCULATION ---

# List of aggregate countries/regions to exclude from median calculation
AGGREGATE_COUNTRIES = [
    "World", "Africa", "Americas", "Asia", "Europe", "Oceania",
    "High income countries", "Low-income countries", "Middle-income countries",
    "Upper-middle-income countries", "Lower-middle-income countries",
    "European Union", "Sub-Saharan Africa", "Latin America and the Caribbean",
    "More Developed Regions", "Less Developed Regions",
    "Central and Southern Asia", "Eastern and South-Eastern Asia",
    "Northern Africa and Western Asia", "Europe and Northern America"
]

# Columns for which we need to calculate the global median default
MEDIAN_COLS = [
    'Cereal Consumption Rice',
    'Fruit Consumption Oranges And Mandarines',
    '% Population Aged 0-14',
    'Diet Composition Pulses'
]

DEFAULTS = {}

def calculate_defaults():
    """Calculates and updates the DEFAULTS dictionary with real medians."""
    global DEFAULTS

    try:
        df = pd.read_csv(DATA_PATH)

        # 1. Filter out aggregate countries/regions
        df_clean = df[~df['Country'].isin(AGGREGATE_COUNTRIES)].copy()

        # 2. Calculate the median for each required column
        medians = df_clean[MEDIAN_COLS].median(skipna=True)

        # 3. Store in the DEFAULTS dictionary
        for col in MEDIAN_COLS:
            DEFAULTS[col] = medians[col]

        print("✅ Defaults calculated from data.")

    except FileNotFoundError:
        print(f"❌ Warning: Data file not found at {DATA_PATH}. Using fallback defaults.")
        # Fallback to estimated values if file is not accessible
        DEFAULTS.update({
            'Cereal Consumption Rice': 50.0,
            'Fruit Consumption Oranges And Mandarines': 15.0,
            '% Population Aged 0-14': 25.0,
            'Diet Composition Pulses': 1.5
        })
    except KeyError as e:
        print(f"❌ Warning: Column {e} not found in data. Using fallback defaults.")
        # Fallback in case of column name mismatch
        DEFAULTS.update({
            'Cereal Consumption Rice': 50.0,
            'Fruit Consumption Oranges And Mandarines': 15.0,
            '% Population Aged 0-14': 25.0,
            'Diet Composition Pulses': 1.5
        })

# Calculate defaults when the config file is imported
calculate_defaults()

if __name__ == '__main__':
    # Print the calculated defaults when running the script directly
    print("\nCalculated DEFAULTS for Model Imputation:")
    for k, v in DEFAULTS.items():
        print(f"  {k}: {v:.3f}")