# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nydhsnt8BaJm26pLdwiA2DDtpzhMSbnO
"""

import pandas as pd
import joblib
import config
import numpy as np

class HealthPredictor:
    def __init__(self):
        self.model = None
        self.feature_names = None
        self._load_artifacts()

    def _load_artifacts(self):
        """Loads the trained model and feature list from disk."""
        try:
            self.model = joblib.load(config.MODEL_PATH)
            self.feature_names = joblib.load(config.FEATURE_PATH)
            print("✅ Model and Feature List loaded successfully.")
        except FileNotFoundError as e:
            print(f"❌ critical Error: Artifacts not found. {e}")
            self.model = None

    def preprocess(self, input_payload: dict) -> pd.DataFrame:
        """
        Transforms raw user input into the exact format the model needs.
        1. Applies Global Defaults (for inputs the user didn't provide).
        2. Calculates Engineered Features (Math).
        3. Orders columns to match training data.
        """
        # 1. Start with Defaults, then override with User Input
        # This ensures every required field exists
        data = config.DEFAULTS.copy()
        data.update(input_payload)

        # 2. Feature Engineering (Must match Notebook 3 Logic!)
        # ---------------------------------------------------------

        # A. Risk_Metabolic_Combo (Sugar * Fat)
        sugar = data.get('Diet Composition Sugar', 0.0)
        fat = data.get('Diet Calories Fat', 0.0)
        data['Risk_Metabolic_Combo'] = sugar * fat

        # B. Ratio_Veg_to_Grain (Veg / (Wheat + Rice + 1))
        veg = data.get('Vegetable Consumption', 0.0)
        wheat = data.get('Cereal Consumption Wheat', 0.0)
        rice = data.get('Cereal Consumption Rice', 0.0)
        data['Ratio_Veg_to_Grain'] = veg / (wheat + rice + 1.0)

        # ---------------------------------------------------------

        # 3. Convert to DataFrame
        df = pd.DataFrame([data])

        # 4. Reorder Columns
        # If we don't do this, the model might get "Age" where it expects "Wheat"
        try:
            df = df[self.feature_names]
        except KeyError as e:
            missing_cols = list(set(self.feature_names) - set(df.columns))
            raise ValueError(f"Input data is missing features required by the model: {missing_cols}")

        return df

    def predict(self, input_payload: dict) -> dict:
        """
        The main public function. Takes a dictionary, returns a prediction.
        """
        if self.model is None:
            return {"error": "Model not initialized. Check .pkl files."}

        try:
            # Step 1: Process Data
            processed_df = self.preprocess(input_payload)

            # Step 2: Inference
            prediction = self.model.predict(processed_df)[0]

            # Step 3: Return clean result
            return {"mortality_rate": round(float(prediction), 4)}

        except Exception as e:
            return {"error": str(e)}

# --- Self-Test Block ---
# This runs only if you run 'python inference.py' directly
if __name__ == "__main__":
    predictor = HealthPredictor()

    # Simulate a user from the App
    test_input = {
        '% Population Aged 65+': 12.5,
        'Gender': 0, # Both
        'Cereal Consumption Wheat': 200.0,
        'Diet Composition Sugar': 15.0
    }

    result = predictor.predict(test_input)
    print(f"Test Prediction: {result}")